name: test_chatbot

on:
  push:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
      
    - name: Install bundler
      run: |
        gem install bundler:2.2.26
        
    - name: Install dependencies
      run: |
        gem install geocoder
    - name: run script
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        ruby ivan-bot.rb
